[package]
name = "voting-server"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
voting-errors = { path = "../voting-errors" }
voting-types = { path = "../voting-types" }
voting-polls = { path = "../voting-polls" }
voting-solana = { path = "../voting-solana" }
